---
version_id: 9.0
id: rhel
instance:
  create:
    image-name: ibm-redhat-9-2-minimal-amd64-3
    network_name: sn-20240306-02
    private_key: test-jenkins
    group_access: flick-outgoing-rejoicing-broadways
    profile: bx2-2x8

  setup:  |
    #cloud-config
    disable_root: false
    ssh_pwauth: true

    groups:
      - cephuser

    users:
      - name: cephuser
        primary-group: cephuser
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX7FADv2xCMJHhB7LapGGDpiAWiXewpa+zjXeORTbPrxTCFu/ct9N9fXlsngAA1fZ1mJme+ynNIm9OSZiqObgKGaZnFlnb8yiEwvslCZtd6TXcnetWw5PDXpq28NNWISNGoH4snOloohJWbGYYAadTD5wIAcOx1xPoPrz50DBJuEpobWa49rAoqRTN678yDWguA83h5PtYY6sBfm5UABKcaQsNiNHzyVNHxMvKJ5u4qdnA126rPNVxDZfLGEZSIurlThuD2XOp0txEiGRuokYW1/0c3KNnFn9aesOttNhw1EurpPWjw3nHvNfjA3NggMQwkPCHJCRTukq4mz9Db6SdwQpHW/32Jwyf6PMgy5UrvaQucPYbJ7urFGWho73FxGgsw454GUEdL+ukifl1wvms/19APPcCZE5FZcSlP3pv/wLEtQbTCIjs8cceVZYUmWUUpdWiQ7u0SpzS9xpH3homY969lMqI0PQYF48unOUlHafV0/NGIi+5f4uKCKxn2bk= amk@amk.remote.csb
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDpMo55n3ZYXae+1obAdb2TzLMCHjLUkGFRsQpvsC48Ptw2dniYDbqiqW95q+EYrHvAX8nVS7YgYhRfzmcZwN0ABuv8VpJ5iSUTP9E4DG2g/YAz3r+UZzihTxWiwRkMuMWFUtYYVJz4ggpVa6XD++9yYaeJ/XYD4oJVWhB9RRr7VVWEhM2Q9HwMYaqNl3caB80c/8hPkp8lbpRI5xMm4YUA1Bw3XDAOGSxpzS9dwZUe3+JwjXEd7i2JqjO98P0AtOI/JmhYD/O61FM6dxgyHi4uksnpfuvMxagjEZ976fZwWnPEGs88iFmtH9UmVcmo1JToMOxnrTR/jdeNAnINHIkjvC8MIfDefIUtA2itUCegf+aHF2W/oOS82+XloVmiY7Wve617QG21z5B+60jl25QX8VC7bPpZrXG5QZIWZI1WFVoplWbrrLr166ju0zAiU4Z3+AuafivHiyt56FT7AcJVVX8f5z2mD8h8ADWg5eiFjzmxVCkZ7GI/vZtt+GF+GOTkWkO+UW4BaTgv6AE2MDKfq+FlYeI7d+lem+AmBntvbQrLnT5XjY8fb1Gm8g+r3doYoOSnVaOaI+EPRUkUJActRiD7EEfBkU51f/ij2e12PAYswjuum6pX7n+JS+k6f92DM8h3VRuoNfr0n8PifrgMiFgixM4wb9ljklF1wlesYw== jenkins@ceph-qe-jenkins

    chpasswd:
      users:
        - name: cephuser
          password: $y$j9T$PxJ09a3yVNnPj0Veb8QDT.$bdWoyLq1IdGwlimyJC98P5OsSFE2w7.9ac68z4eoa01
        - name: root
          password: $y$j9T$L0/xJyxgqCPIezC0dp/0/0$KawKfTR2FhliH9YrG4/30wot90M3xtF03K1XwGnYz2A
      expire: false

    runcmd:
      - sed -i -e 's/^Defaults\s\+requiretty/# \0/' /etc/sudoers
      - sed -i -e 's/#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
      - systemctl restart sshd
      - curl -k -o /etc/pki/ca-trust/source/anchors/ceph-qe-ca.pem http://10.240.64.5/.ceph-qe-ca.pem
      - curl -k -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt http://10.240.64.5/.RH-IT-Root-CA.crt
      - update-ca-trust
      #- yum-config-manager --add-repo https://10.245.4.89/repos/8/lab-extras.repo
      #- echo "net.core.default_qdisc=netem" > /etc/sysctl.d/1000-qdisc.conf
      - touch /ceph-qa-ready
