# Temporary cluster configuration file and
# will be removed once nautilus pipeline is in place
# OSD_SCENARIO(osd-scenario) works with
#    ansi_config['osd_scenario'] = lvm and
#    "mixed_lvm_config" option set
#
# OSD_SCENARIO 0 - osd_scenario1
#--------------------------------
#lvm_volumes="[
#  {'data':'data-lv1','data_vg':'vg1'},
#  {'data':'data-lv2','data_vg':'vg1','db':'db-lv1','db_vg':'vg1'},
#  {'data':'data-lv3','data_vg':'vg1','wal':'wal-lv1','wal_vg':'vg1'},
#  {'data':'data-lv4','data_vg':'vg1','db':'db-lv2','db_vg':'vg1','wal':'wal-lv2','wal_vg':'vg1'}]"
#
# OSD_SCENARIO 1 - osd_scenario1_dmcrypt
#---------------------------------------
#lvm_volumes="[
#  {'data':'data-lv1','data_vg':'vg1'},
#  {'data':'data-lv2','data_vg':'vg1','db':'db-lv1','db_vg':'vg1'},
#  {'data':'data-lv3','data_vg':'vg1','wal':'wal-lv1','wal_vg':'vg1'},
#  {'data':'data-lv4','data_vg':'vg1','db':'db-lv2','db_vg':'vg1','wal':'wal-lv2','wal_vg':'vg1'}]" dmcrypt='True'
#
# OSD_SCENARIO 2 - osd_scenario2
#-------------------------------
# lvm_volumes="[
#  {'data':'/dev/vdc1','db':'/dev/vdc2','wal':'/dev/vdc3'},
#  {'data':'/dev/vdd','db':'/dev/vdc4','wal':'/dev/vdc5'},
#  {'data':'/dev/vde'}]"
#
# OSD_SCENARIO 3 - osd_scenario2_dmcrypt
#----------------------------------------
# lvm_volumes="[
#  {'data':'/dev/vdc1','db':'/dev/vdc2','wal':'/dev/vdc3'},
#  {'data':'/dev/vdd','db':'/dev/vdc4','wal':'/dev/vdc5'},
#  {'data':'/dev/vde'}]" dmcrypt='True'
#
# OSD_SCENARIO 4 - osd_scenario3_dmcrypt
#----------------------------------------
# lvm_volumes="[
#  {'data':'/dev/vdc','db':'db-lv1','db_vg':'vg1','wal':'wal-lv1','wal_vg':'vg1'},
#  {'data':'data-lv1','data_vg':'vg1','db':'/dev/vde2','wal':'/dev/vde3'},
#  {'data':'/dev/vde1'}]" dmcrypt='True'
#
# OSD_SCENARIO 5 - osd_scenario3_dmcrypt
#----------------------------------------
# lvm_volumes="[
#  {'data':'/dev/vdc','db':'db-lv1','db_vg':'vg1','wal':'wal-lv1','wal_vg':'vg1'},
#  {'data':'data-lv1','data_vg':'vg1','db':'/dev/vde2','wal':'/dev/vde3'},
#  {'data':'/dev/vde1'}]" dmcrypt='True'
#
# OSD_SCENARIO 6 - osd_scenario4
#----------------------------------
# devices="['/dev/vdb', '/dev/vdc', '/dev/vdd', '/dev/vde']"
#
# OSD_SCENARIO 7 - osd_scenario4_dmcyrpt
#----------------------------------------
# devices="['/dev/vdb', '/dev/vdc', '/dev/vdd', '/dev/vde']" dmcrypt='True'
#
globals:
  - ceph-cluster:
      name: ceph
      node1:
        role:
          - mon
          - mgr
          - installer
          - osd
        osd-scenario: 1                  # pick osd scenario[0-8], OSD_SCENARIO 1
        no-of-volumes: 4
        disk-size: 15
      node2:
        role:
          - mon
          - client
          - osd
        osd-scenario: 5                  # OSD_SCENARIO 5
        no-of-volumes: 4
        disk-size: 15
      node3:
        role:
          - mon
          - osd
        osd-scenario: 3                  # OSD_SCENARIO 3
        no-of-volumes: 4
        disk-size: 15
      node4:
        role:
          - grafana
