---

- name: Add host (mon) to cluster with admin label
  hosts: installer
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Add mon node with admin label
      ceph_orch_host:
        set_admin_label: true
        name: "{{ node }}"
        address: "{{ ip_address }}"
        labels: "{{ label }}"
