---

- name: deploy osd service
  hosts: installer
  become: true
  gather_facts: true
  tasks:
    - name: apply osd spec
      ceph_orch_apply:
        spec: |
          service_type: osd
          service_id: osd
          placement:
            host_pattern: '*'
            label: "{{ label }}"
          spec:
            data_devices:
              all: true
