---

- name: Restart service
  hosts: installer
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Restart the service
      ceph_orch_daemon:
        state: restarted
        daemon_id: "{{ daemon_id }}"
        daemon_type: "{{ daemon_type }}"
