- name: Set ceph config "option" to "value"
  hosts: installer
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Set ceph config
      ceph_config:
        action: set
        who: "{{ who }}"
        option: "{{ option }}"
        value: "{{ value }}"

    - name: Validate ceph config
      ceph_config:
        action: get
        who: "{{ who }}"
        option: "{{ option }}"
      register: set_ceph_config_out
      failed_when: "{{ value }} != {{ set_ceph_config_out.stdout }}"
